name: clipboard
version: "0.8.0"
summary: The ultimate clipboard manager for the terminal
description: |
  The Clipboard Project is one of the most advanced clipboard managers ever.
  Cut, copy, and paste anything, anytime, anywhere with unlimited capacity, clipboards, and history.
  It's feature packed and easy to use by anybody.
confinement: strict
base: core22
parts:
  clipboard:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_LIBDIR=bin
    source-type: git
    source: https://github.com/Slackadays/Clipboard
    source-branch: main
    build-packages:
      - g++
      - make
      - cmake
      - libasound2-dev
      - liburing-dev
      - libx11-dev
      - libwayland-dev
      - wayland-protocols
    stage-packages:
      - libasound2-dev
      - liburing-dev
      - libx11-dev
      - libwayland-dev
apps:
  clipboard:
    command: usr/local/bin/cb
    plugs:
      - alsa
      - x11
      - wayland
      - home
      - removable-media