set -l commands cut copy paste clear show edit add remove note swap status info load import export history ignore search help

complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a cut -d 'cut something'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a copy -d 'copy something'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a paste -d 'paste something'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a clear -d 'clear clipboard'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a show -d 'show clipboard content'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a edit -d 'edit clipboard content'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a add -d 'add something to clipboard'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a remove -d 'remove something from clipboard'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a note -d 'add note to clipboard'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a swap -d 'swap clipboard content'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a status -d 'show status'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a info -d 'show clipboard info'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a load -d 'load clipboard into other clipboard'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a import -d 'import clipboard from file'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a export -d 'export clipboard to file'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a history -d 'show clipboard history'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a ignore -d 'ignore content'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a search -d 'search clipboard content'
complete -c cb -f -n "not __fish_seen_subcommand_from $commands" -a help -d 'show help for CB'